# ================================================================
#  <TITLE>  -  generated by PandorumLLM Launcher Creator
#  Placeholders <MODEL_PATH>, <MMPROJ_PATH>, <DRAFT_PATH>, <SELF_PATH>
#  are filled in at create time. Lines whose placeholder is set to
#  N/A are removed from the generated file automatically.
# ================================================================

# --- GPU pinning (edit to taste) --------------------------------
# Pin by UUID for deterministic card selection across reboots:
#   nvidia-smi -L   -> copy the GPU-xxxxxxxx UUID you want
$env:CUDA_VISIBLE_DEVICES = "<GPU_ID>"

$exe = "<LLAMA_EXE>"

$args_ = @(
    "--model", "<MODEL_PATH>",
    "--mmproj", "<MMPROJ_PATH>",
    "--model-draft", "<DRAFT_PATH>",
    "--port", "<PORT>",
    "--host", "127.0.0.1",
    "--ctx-size", "16384",
    "--n-gpu-layers", "99",
    "--flash-attn", "on",
    "--cache-ram", "0",
    # --- Sampler chain ---
    "--samplers", "penalties;dry;top_n_sigma;top_k;typ_p;top_p;min_p;xtc;temperature",
    "--ctx-checkpoints", "0"
)

Write-Host ("Launching: {0}" -f (Split-Path "<MODEL_PATH>" -Leaf))
& $exe @args_

# Crash-restart supervisor line (PandorumLLM/stack convention):
& "<SELF_PATH>"
