# ================================================================
#  <TITLE>  -  generated by PandorumLLM Launcher Creator
#  Placeholders <MODEL_PATH>, <MMPROJ_PATH>, <DRAFT_PATH>, <SELF_PATH>
#  are filled in at create time. Lines whose placeholder is set to
#  N/A are removed from the generated file automatically.
# ================================================================

# --- GPU pinning (edit to taste) --------------------------------
# Pin by UUID for deterministic card selection across reboots:
#   nvidia-smi -L   -> copy the GPU-xxxxxxxx UUID you want
$env:CUDA_VISIBLE_DEVICES = "<GPU_ID>"

$exe = "<LLAMA_EXE>"

$args_ = @(
    "--model", "<MODEL_PATH>",
    "--mmproj", "<MMPROJ_PATH>",
    "--model-draft", "<DRAFT_PATH>",
    "--port", "<PORT>",
    "--host", "127.0.0.1",
    "--ctx-size", "16384",
    "--n-gpu-layers", "99",
    "--flash-attn", "on",
    "--cache-ram", "0",
    # --- Sampler chain ---
    "--samplers", "penalties;dry;top_n_sigma;top_k;typ_p;top_p;min_p;xtc;temperature",
    "--ctx-checkpoints", "0"
)

Write-Host ("Launching: {0}" -f (Split-Path "<MODEL_PATH>" -Leaf))

# llama-server's own output goes straight to this console and this log, unfiltered.
# The panel reads THESE lines to report what the server allocated - weights, KV,
# compute buffers, the draft split - so nothing here may reformat or swallow them.
& $exe @args_
$code = $LASTEXITCODE

# The panel watches for this exact sentence to tell a server that died from one
# still loading. llama-server never prints it, so the launcher must.
if ($code -ne 0) {
    Write-Host ""
    Write-Host ("Server process exited before it became ready (exit {0})" -f $code) -ForegroundColor Red
} else {
    Write-Host ""
    Write-Host ("Server process exited before it became ready (exit 0 - stopped or never bound)") -ForegroundColor Yellow
}

# No automatic relaunch. This file used to re-invoke itself here, so a server that
# could not start looped instead of stopping - and the console that held the reason
# was replaced by the next attempt before anyone could read it. Restart from the
# panel, which now says why the last one ended.
Write-Host "This window stays open so the lines above can be read. Close it when done." -ForegroundColor DarkGray
if ($Host.Name -eq "ConsoleHost") { [void][System.Console]::ReadKey($true) }
exit $code
