# TEMPLATE_NAME: Pinned server (one card, no fitting) - the server card default
# ================================================================
#  <TITLE>  -  generated by PandorumLLM from the server card.
#
#  A SERVER TEMPLATE. These live in server-templates\ and are built
#  for the fleet: one card, pinned, no spilling. The Launcher Creator
#  has its own templates in templates\ and is a separate feature -
#  its files are never offered here, because a template written for
#  a single-GPU PC cannot pin a card and a fleet server must.
#
#  Placeholders <MODEL_PATH>, <MMPROJ_PATH>, <DRAFT_PATH>, <GPU_ID>,
#  <PORT>, <TITLE> and <LLAMA_EXE> are filled in when the card writes
#  this file - these are the ones the panel substitutes, and a name it
#  does not know would survive into the launcher as literal text.
#  The GPU pin is additionally enforced by the panel on write. Lines whose
#  placeholder is N/A are removed automatically.
# ================================================================
$Host.UI.RawUI.WindowTitle = "<TITLE>"
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()

# ONE card, and only this one. CUDA_VISIBLE_DEVICES masks every other GPU out of
# the process, so llama.cpp cannot place a layer anywhere else even if it wants
# to. Without this line a fleet server sees the whole rig and fits across it.
$env:CUDA_VISIBLE_DEVICES = "<GPU_ID>"

$llamaArgs = @(
    # Model ---------------------------------------------------
    "--model", "<MODEL_PATH>"
    "--mmproj", "<MMPROJ_PATH>"
    "--model-draft", "<DRAFT_PATH>"
    # Server --------------------------------------------------
    "--port", "<PORT>"
    "--host", "127.0.0.1"
    "--alias", "<TITLE>"
    # GPU -----------------------------------------------------
    # Every layer on the card, and fitting OFF so llama.cpp keeps them there.
    # --fit defaults to ON upstream: left unsaid it redistributes the model
    # across whatever it can see and spills the remainder into host RAM.
    "--n-gpu-layers", "99"
    "--fit", "off"
    # dio, not the default mmap. Memory-mapped weights stay host-resident and get
    # spread across whatever llama.cpp can reach - measured on a three-card rig,
    # "auto" put one model across three GPUs and system RAM while "dio" kept it on
    # the pinned card. This decides WHERE the weights live, not just load speed.
    "--load-mode", "dio"
    "--flash-attn", "on"
    # Context and cache ---------------------------------------
    "--ctx-size", "8192"
    # Both zeros explicit, and both must be. --cache-ram lets the KV cache spill
    # into system RAM; --ctx-checkpoints keeps rollback copies of a slot's context
    # in host memory (llama.cpp's own default is 8). Left unsaid they are the
    # reason a model "fits" and then runs slow off system memory instead of
    # failing honestly.
    "--cache-ram", "0"
    "--ctx-checkpoints", "0"
    # Logging -------------------------------------------------
    "-lv", "4"
)

# llama-server's own output reaches this console and the panel's log unfiltered.
# The VRAM report on the server card is parsed from THESE lines, so nothing here
# may reformat, filter or swallow them.
& "<LLAMA_EXE>" @llamaArgs
$code = $LASTEXITCODE

# The panel tells a server that DIED from one still loading by this exact
# sentence. llama-server never prints it, so the launcher must.
Write-Host ""
Write-Host ("Server process exited before it became ready (exit {0})" -f $code) -ForegroundColor Red
Write-Host "This window stays open so the lines above can be read." -ForegroundColor DarkGray
if ($Host.Name -eq "ConsoleHost") { [void][System.Console]::ReadKey($true) }
exit $code
